[template]
name = "Lazygit"
target = "~/.config/lazygit/themes/noctalia.yml"

[content]
inline = '''
gui:
  theme:
    activeBorderColor:
      - "{{ colors.primary.hex }}"
      - bold
    inactiveBorderColor:
      - "{{ colors.outline.hex }}"
    optionsTextColor:
      - "{{ colors.secondary.hex }}"
    selectedLineBgColor:
      - "{{ colors.surface_container_high.hex }}"
    cherryPickedCommitBgColor:
      - "{{ colors.tertiary_container.hex }}"
    cherryPickedCommitFgColor:
      - "{{ colors.on_tertiary_container.hex }}"
    markedBaseCommitBgColor:
      - "{{ colors.yellow.hex }}"
    unreadGroupBgColor:
      - "{{ colors.surface_container.hex }}"
'''
