[template]
name = "PrismLauncher"
target = "~/.local/share/PrismLauncher/themes/Matugen/theme.json"

[content]
inline = '''
{
  "colors": {
    "AlternateBase": "{{ colors.surface.hex }}",
    "Base": "{{ colors.surface.hex }}",
    "BrightText": "{{ colors.secondary.hex }}",
    "Button": "{{ colors.surface_container.hex }}",
    "ButtonText": "{{ colors.on_surface.hex }}",
    "Highlight": "{{ colors.primary.hex }}",
    "HighlightedText": "{{ colors.on_primary.hex }}",
    "Link": "{{ colors.primary.hex }}",
    "Text": "{{ colors.on_surface.hex }}",
    "ToolTipBase": "{{ colors.surface_container.hex }}",
    "ToolTipText": "{{ colors.on_surface.hex }}",
    "Window": "{{ colors.surface.hex }}",
    "WindowText": "{{ colors.on_surface.hex }}",
    "fadeAmount": 0.5,
    "fadeColor": "{{ colors.surface_container.hex }}"
  },
  "name": "Matugen",
  "widgets": "Fusion"
}
'''
